# April 23, 2020
# LML

# Running community ordinations for soil fungi across the MUD transect with updated data. The code from the original ordination was written a long time ago when I didn't know what I was doing in R and it's a mess

#### Load packages
#install.packages()
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl) #for importing excel files
library(vegan)
library(MASS)
library(grid)
library(VennDiagram)

#~*~*~*~*~*~*~*~ Load Data ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

#OTU x trt table
#******LUKAS is this the most up-to-date version for the OTU x treatment data? It is the data I used in the original ordination so that's why I use it here
trt_raw <- read_csv('Old_Analyses/MUD_fungi_OTU_ITS_VST.csv') 

# Names for OTUs generated by Lee Taylor
names_raw <- read_excel("R_files/MUD_taxa_PROTAX_12-30-19.xlsx")
names_raw <- dplyr::rename(names_raw, Lees_id = "Lee's ID") #remove apostrophe

#~*~*~*~*~*~*~*~ Organize and clean ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*

delete_otu <- names_raw %>%
  dplyr::filter(Lees_id == 'DELETE')

trt <- trt_raw %>%
  dplyr::select(-contains("SPEGAR")) %>% #remove columns with "SPEGAR" because those are for a different project
  dplyr::select(-contains("mock")) %>% #remove columns with "mock"
  mutate(otu_sum = rowSums(.[2:57])) %>% #find OTUs only in SPEGAR (so =0)
  dplyr::filter(otu_sum > 0) %>% #remove SPEGAR only OTUs
  subset(select = -otu_sum) #get rid of otu sums

# Exported data to transpose it in excel because I can't figure out how to do it in R. t() turns it into a matrix that I just can't work with. I tried to learn but I hit my set time point where "learning" turns into "wasted time" so I just did it in excel. Ideally this step will be replaced with properly doing it in R at some point.
#write.csv(trt, "R_files/otu_X_trt_to_transpose_200424.csv")
trt_trans <- read_csv("R_files/otu_x_trt_transposed_in_excel_200424.csv")

# delete OTUs that are contamination (based on Lee's ID)
trt_trans <- trt_trans[, !(colnames(trt_trans) %in% c("OTU10","OTU40","OTU763"))]
trt_trans_v <- trt_trans #making a copy I can use for making Venn diagrams below

trt_trans_rownames <- trt_trans[1] #list of names so I can add them back in later. Not the idea way, but this row naming business doesn't work, namely the rownames don't hold
trt_trans_rownames$number <- 1:nrow(trt_trans_rownames) #this variable can get merged with later dataset

rownames(trt_trans) <-trt_trans$OTU #turning first row into rownames because transpose spits out a matrix that doesn't have these
trt_trans <- trt_trans[,-1] #then droping the otu column bc they are now rownames (but the rownames don't acutally stay....)

#library(vegan)
#library(MASS)     
m1 <- metaMDS(trt_trans, distance = "bray", k = 3, trymax = 500,
              autotransform =FALSE,  
              wascores = TRUE, expand = TRUE,
              trace = 1, plot = TRUE,)

#plot ordination
plot(m1, display = c("sites"), choices = c(1,2),
     type = "t", shrink = TRUE)
plot(m1, display = c("sites"), choices = c(1,3),
     type = "t", shrink = TRUE)
plot(m1, display = c("sites"), choices = c(2,3),
     type = "t", shrink = TRUE)
scores(m1, display = c("sites", "species"), shrink = FALSE)

### Examining nmds output
print (m1)
#str(m1)     
m1$species
m1$points
#m1$ndim

#### Making some datasets to graph
###Looking at treatment (location and plant species)
trt_scores <- as.data.frame(m1$points) #adding MDS scores
trt_scores$number <- row.names(trt_scores) #adding numbers to merge with other data
trt_scores$number <- as.character(trt_scores$number) #changing to be similar
trt_trans_rownames$number <- as.character((trt_trans_rownames$number)) #changing to be similar so the datasets can be merged
trt_scores <- full_join(trt_scores, trt_trans_rownames, by = "number")

trt_scores <- trt_scores %>%
  dplyr::select(-number) %>% #get rid of meaningless number column
  dplyr::rename(id = OTU) %>% #renaming column
  mutate(s = id) %>% 
  separate(s, c("junk", "location", "spp", "rep")) %>% #split label into useful bits
  dplyr::select(-junk)

### Looking at fungal OTUs
otu_scores <- as.data.frame(m1$species) #make dataset with MDS scores
otu_scores$OTU <- row.names(otu_scores) #pulling OTU names out of row names and maing them a column

names <- names_raw %>%
  dplyr::select(OTU, Lees_id) #just pull out Lees names

otu_scores <- left_join(otu_scores, names) #merging NMDS scores with OTU names

### Making fungal dataset so they can be vectors on graph. (all based on some website...). I don't actually want to graph all of them on a figure because that would be too much, but could potentially just graph the most influential ones.
vec.sp <- envfit(m1$points, trt_trans, perm=1000)
vec.sp.df <- as.data.frame(vec.sp$vectors$arrows*sqrt(vec.sp$vectors$r))
vec.sp.df$species <- rownames(vec.sp.df)

vec.sp.df <- left_join(vec.sp.df, names, by = c("species" = "OTU")) #attach Lee's names to the vectors


# Saving final files so those can just be called in next time. I'm still not sure what format it is best to save data as, so I'll just stick with RData
save(otu_scores, file = "R_files/Fungal_otu_ordination_scores.RData")
save(trt_scores, file = "R_files/site_plant_ordination_scores.RData")
save(vec.sp.df, file = "R_files/OTU_vectors_for_ordination.RData")
save(m1, file = "R_files/CommComp_ordination_test_results.RData")




## ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
## ~*~*~*~*~*~*~*~*~*~*~*~*~ Graphing ~*~*~*~*~*~*~*~*~*~*~*~*~
## ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
# By site; Colored based on location
ord_fig <- ggplot((data = trt_scores), mapping = aes(x = MDS1, y = MDS2)) +
  geom_point(aes(color = location, fill = location, shape = spp), size = 4) + 
  scale_shape_manual(values = c(25, 22, 21, 24)) +
  #geom_segment(data=vec_sort_c,aes(x=0,xend=MDS1/2,y=0,yend=MDS2/2),arrow = arrow(length = unit(0.5, "cm")),colour="grey",inherit_aes=FALSE) + 
  #geom_text(data=vec_sort_d ,aes(x=MDS1/2,y=MDS2/2,label=Lees_id),size=4)+
  theme_classic() +
  scale_fill_manual(values = c("saddlebrown","brown1", "darkturquoise")) + #CHANGE!
  scale_color_manual(values = c("black", "black", "black")) +
  theme(panel.border = element_rect(color = "black", size = 1, fill = NA),#black line all around graph
        text = element_text(size = 12),
        #legend.key.size = unit(4, "lines"),
        #legend.spacing = unit(0.5, "lines"),
        legend.title = element_blank(),
        legend.position = "top"
  )
ord_fig

# By site; colored based on species
ord_fig_spp <- ggplot((data = trt_scores), mapping = aes(x = MDS1, y = MDS2)) +
  geom_point(aes(color = spp, fill = spp, shape = location), size = 4) + 
  scale_shape_manual(values = c(21, 22, 24)) +
  theme_classic() +
  scale_fill_manual(values = c("saddlebrown","brown1", "darkturquoise","bisque")) +
  scale_color_manual(values = c("black", "black", "black", "black")) +
  theme(panel.border = element_rect(color = "black", size = 1, fill = NA),#black line all around graph
        text = element_text(size = 12),
        #legend.key.size = unit(4, "lines"),
        #legend.spacing = unit(0.5, "lines"),
        legend.title = element_blank(),
        legend.position = "top"
  )
ord_fig_spp

## Examining fungal OTUs.
## There seems to be decent separation among sites and plant species to some extent along the first axis, so what fungi are strongly associated with MDS1? Trying several ways of picking the top fungal taxa adn then I'll compare the results


vec_sort_a <- vec.sp.df %>% dplyr::arrange(desc(abs(MDS1)), abs(MDS2)) #sorts first in descending order of MDS1 then assending order of MDS2

vec_sort_b <- vec.sp.df %>%
  filter(abs(MDS2) < 0.1) %>% #filter out species that have large MDS2. 0.1 seems like a decent cut off
  #dplyr::arrange(desc(abs(MDS1))) %>% #this step was good for visualizations
  filter(abs(MDS1) > 0.5)

vec_sort_c <- vec.sp.df %>%
  filter(abs(MDS2) < 0.1) %>% #filter out species that have large MDS2. 0.1 seems like a decent cut off
  #dplyr::arrange(desc(abs(MDS1))) %>% #this step was good for visualizations
  filter(abs(MDS1) > 0.45) #allows a few more species in

vec_sort_d <- vec.sp.df %>%
  #filter(abs(MDS2) < 0.1) %>% #filter out species that have large MDS2. 0.1 seems like a decent cut off
  #dplyr::arrange(desc(abs(MDS1))) %>% #this step was good for visualizations
  filter(abs(MDS1) > 0.45) #allows a few more species in


vec_pick <- ggplot((data = vec_sort_b), mapping = aes(x = MDS1, y = MDS2)) +
  geom_point() 
vec_pick


###### Looking at shared species across different combinations of treatments
## GOAL: venn diagrams for OTU present for LATR ecotone vs shrub, ecotone LATR vs PLJA and ecotone LATR vs BOER

#split the first column called "OTU" into separate columns based on where the dots are, then make a new variable with site and species merged into one, then summarize by site_spp by adding values for each OTU across all the reps, then change to presense/absense; then... then make speapate datasets for each comparision of interst
tester <- trt_trans_v %>%
  gather("taxa", "abun", -OTU) %>%
  #pivot_longer(cols = OTU, names_to = "taxa", values_to = "abun")
  separate(OTU, c("project", "site", "spp", "rep", "\\.")) %>% #separate label info
  tidyr::unite(site_spp, site, spp) %>% #makes a site_spp column
  group_by(site_spp, taxa) %>%
  dplyr::summarise(aveabun = mean(abun))

Eco_boer_latr <- tester %>%
  filter(site_spp == "Ecotone_BOER" | site_spp == "Ecotone_LATR") %>%
  spread(site_spp, aveabun) %>%
  mutate(BOER = if_else(Ecotone_BOER >0, 5, 0)) %>%
  mutate(LATR = if_else(Ecotone_LATR >0, 1, 0)) %>%
  mutate(both = BOER + LATR) %>%
  count(both)
#hist(Eco_boer_latr$both)

grid.newpage()
weeell <- draw.pairwise.venn(1347, 1568, 873, c("Ecotone LATR", "Ecotone BOER"), cat.dist = -0.05, fill = c("darkturquoise", "saddlebrown"))
grid.draw(weeell)  
  

Eco_plja_latr <- tester %>%
  filter(site_spp == "Ecotone_PLJA" | site_spp == "Ecotone_LATR") %>%
  spread(site_spp, aveabun) %>%
  mutate(PLJA = if_else(Ecotone_PLJA >0, 5, 0)) %>%
  mutate(LATR = if_else(Ecotone_LATR >0, 1, 0)) %>%
  mutate(both = PLJA + LATR) %>%
  count (both)
#hist(Eco_plja_latr$both)  

grid.newpage()
hmmm <- draw.pairwise.venn(1347, 1493, 844, c("Ecotone LATR", "Ecotone PLJA"), cat.dist = -0.05, fill = c("darkturquoise", "bisque"))
grid.draw(hmmm)

latr_eco_shrub <- tester %>%
  filter(site_spp == "Shrub_LATR" | site_spp == "Ecotone_LATR") %>%
  spread(site_spp, aveabun) %>%
  mutate(eco = if_else(Shrub_LATR >0, 5, 0)) %>%
  mutate(shrub = if_else(Ecotone_LATR >0, 1, 0)) %>%
  mutate(both = shrub + eco) %>%
  count(both)
hist(latr_eco_shrub$both)  

grid.newpage()
grrr <- draw.pairwise.venn(1347, 1431, 791, c("shrub LATR", "ecotone BOER"), cat.dist = -0.05, fill = "darkturquoise")
grid.draw(grrr)

grid.newpage()



#### graveyard #########
test <- otu_scores[with(otu_scores, order(-MDS1)),] #sort desending
head(test)
test2 <- otu_scores[with(otu_scores, order(MDS1)),] #sort desending
head(test2)